apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: danklinux
resources:
- deployment.yaml
- svc.yaml
- ingress.yaml
- server-deployment.yaml
- server-svc.yaml
- server-ingress.yaml