---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlx-docs-deployer
  namespace: danklinux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dlx-docs-deployer
  namespace: danklinux
rules:
- apiGroups: [""]
  resources: ["services", "secrets", "configmaps", "pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dlx-docs-deployer
  namespace: danklinux
subjects:
- kind: ServiceAccount
  name: dlx-docs-deployer
  namespace: danklinux
roleRef:
  kind: Role
  name: dlx-docs-deployer
  apiGroup: rbac.authorization.k8s.io
