apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dlx-docs-server-ingress
  namespace: danklinux
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      real_ip_header CF-Connecting-IP;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
        - api.danklinux.com
      secretName: api-danklinux-com-tls
  rules:
    - host: api.danklinux.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dlx-docs-server
                port:
                  number: 8337
